### ISSUE TITLE
Smart retry mechanism

### ISSUE THREAD

**Issue by chronark** [upstash/upstash-kafka#14]
Currently there is a default retry mechanism to retry up to 5 times if upstash returns an error.
That kind of works but is also quite wasteful. For example if an authentication error is returned there is no point in trying again.

I would categorize errors in two categories, retryable and non retryable ones.
For example:

Retryable:
- partition rebalancing

Non retryable
- Authentication
- wrong consumerGroupId or instanceId when trying to delete a consumer group.

**Comment by ogzhanolguncu** [comment]
bump
