### ISSUE TITLE
Authentication issue from Cloudflare workers

### ISSUE THREAD

**Issue by olivier-wd** [upstash/upstash-kafka#47]
Hi,
I'm not able to authenticate on kafka service from Clouflare Worker but can from java with same kafka and same credentials.
This error also occurs when I use cloudflare's link you have on your website (https://cloudflareworkers.com/#...)

I've also tried to create new credential and new kafka and have same error from cloudflare worker only.

Here's the error message : 
```
{
"result" : "",
"error" : "Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256",
"status" : 403
}
```

Regards,

**Comment by chronark** [comment]
You are probably using TCP credentials, but you need the `REST` url, username and password

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/18246773/221157145-62d0fc28-27f8-435b-b08e-bcf7d76e3705.png">

**Comment by olivier-wd** [comment]
No I've verified and I'm using the good ones. In fact username and password are the same.
Also this is why I've specified that issue also occurs with the demo code you provide directly on cloudflare worker website

**Comment by chronark** [comment]
Oh gotcha.
thanks, we'll look into it asap

**Comment by chronark** [comment]
@olivier-wd 
we're going to fix this, in the mean time, you can get the correct authorization header from here:
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/18246773/221167488-9119adf9-6060-43f0-ab00-9fe387ea08a9.png">
